# PySpark MLlib 

This notebook is based on https://github.com/jadianes/spark-py-notebooks

MLlib is Spark's machine learning library.  

## Getting the data

In [1]:
import urllib.request
f = urllib.request.urlretrieve ("http://kdd.ics.uci.edu/databases/kddcup99/kddcup.data_10_percent.gz", "kddcup.data_10_percent.gz")

## Create a PySpark session

In [2]:
import findspark
findspark.init()

import pyspark
from pyspark.sql import SparkSession
conf = pyspark.SparkConf().setAppName('MLlib-PySpark').setMaster('local')
sc = pyspark.SparkContext(conf=conf)
spark = SparkSession(sc)

## Create RDD

In [3]:
data_file = './kddcup.data_10_percent.gz'
raw_data = sc.textFile(data_file)

## Local vectors

A local vector is often used as a base type for RDDs in Spark MLlib. A local vector has integer-typed and 0-based indices and double-typed values, stored on a single machine. MLlib supports two types of local vectors: dense and sparse. A dense vector is backed by a double array representing its entry value, while a sparse vector is backed by two parallel arrays: indices and values.

- For dense vectors, MLlib uses either Python list or the Numpy array type. The later is recommended, so you can simply pass NumPy arrays around.

- For sparse vectors, users can construct a SparseVector object from MLlib or pass SciPy scipy.sparse column vectors if SciPy is available in their environment. The easiest way to create sparse vectors is to use the factory methods implemented in Vectors.

### An RDD of dense vectors

Let's represent each network interaction in our dataset as a dense vector. For that we will use the NumPy array type.

In [4]:
import numpy as np

def parse_interaction(line):
    line_split = line.split(",")
    # keep just numeric and logical values
    symbolic_indexes = [1,2,3,41]
    clean_line_split = [item for i,item in enumerate(line_split) if i not in symbolic_indexes]
    return np.array([float(x) for x in clean_line_split])

vector_data = raw_data.map(parse_interaction)

In [5]:
# Summary statistics
from pyspark.mllib.stat import Statistics 

# Compute column summary statistics.
summary = Statistics.colStats(vector_data)

print('Duration statistics:')
print('Mean: {}'.format(round(summary.mean()[0], 3)))

Duration statistics:
Mean: 47.979


In [8]:
from math import sqrt
def parse_interaction_with_key(line):
    line_split = line.split(",")
    # keep just numeric and logical values
    symbolic_indexes = [1,2,3,41]
    clean_line_split = [item for i,item in enumerate(line_split) if i not in symbolic_indexes]
    return (line_split[41], np.array([float(x) for x in clean_line_split]))

label_vector_data = raw_data.map(parse_interaction_with_key)

def summary_by_label(raw_data, label):
    label_vector_data = raw_data.map(parse_interaction_with_key).filter(lambda x: x[0]==label)
    return Statistics.colStats(label_vector_data.values())

label_list = ["back.","buffer_overflow.","ftp_write.","guess_passwd.",
              "imap.","ipsweep.","land.","loadmodule.","multihop.",
              "neptune.","nmap.","normal.","perl.","phf.","pod.","portsweep.",
              "rootkit.","satan.","smurf.","spy.","teardrop.","warezclient.",
              "warezmaster."]

# get a list of statistics for each label
stats_by_label = [(label, summary_by_label(raw_data, label)) for label in label_list]

# get the duration column

duration_by_label = [(stat[0], np.array([float(stat[1].mean()[0]), float(sqrt(stat[1].variance()[0])), float(stat[1].min()[0]), float(stat[1].max()[0]), int(stat[1].count())])) 
    for stat in stats_by_label]

In [10]:
duration_by_label

[('back.',
  array([1.28915116e-01, 1.11006217e+00, 0.00000000e+00, 1.40000000e+01,
         2.20300000e+03])),
 ('buffer_overflow.',
  array([ 91.7       ,  97.51468501,   0.        , 321.        ,
          30.        ])),
 ('ftp_write.',
  array([ 32.375     ,  47.44903281,   0.        , 134.        ,
           8.        ])),
 ('guess_passwd.',
  array([ 2.71698113, 11.87981054,  0.        , 60.        , 53.        ])),
 ('imap.',
  array([ 6.       , 14.1742404,  0.       , 41.       , 12.       ])),
 ('ipsweep.',
  array([3.44827586e-02, 4.38439193e-01, 0.00000000e+00, 7.00000000e+00,
         1.24700000e+03])),
 ('land.', array([ 0.,  0.,  0.,  0., 21.])),
 ('loadmodule.',
  array([ 36.22222222,  41.40886915,   0.        , 103.        ,
           9.        ])),
 ('multihop.',
  array([184.        , 253.85100617,   0.        , 718.        ,
           7.        ])),
 ('neptune.', array([     0.,      0.,      0.,      0., 107201.])),
 ('nmap.', array([  0.,   0.,   0.,   0., 231

### Correlations
Spark's MLlib supports Pearson’s and Spearman’s to calculate pairwise correlation methods among many series. Both of them are provided by the corr method in the Statistics package.

In [11]:
from pyspark.mllib.stat import Statistics 
correlation_matrix = Statistics.corr(vector_data, method="spearman")

import pandas as pd
pd.set_option('display.max_columns', 50)

col_names = ["duration","src_bytes","dst_bytes","land","wrong_fragment",
             "urgent","hot","num_failed_logins","logged_in","num_compromised",
             "root_shell","su_attempted","num_root","num_file_creations",
             "num_shells","num_access_files","num_outbound_cmds",
             "is_hot_login","is_guest_login","count","srv_count","serror_rate",
             "srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate",
             "diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count",
             "dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate",
             "dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate",
             "dst_host_rerror_rate","dst_host_srv_rerror_rate"]

corr_df = pd.DataFrame(correlation_matrix, index=col_names, columns=col_names)

corr_df

duration  src_bytes  dst_bytes      land  \
duration                     1.000000   0.014196   0.299189 -0.001068   
src_bytes                    0.014196   1.000000  -0.167931 -0.009404   
dst_bytes                    0.299189  -0.167931   1.000000 -0.003040   
land                        -0.001068  -0.009404  -0.003040  1.000000   
wrong_fragment              -0.008025  -0.019358  -0.022659 -0.000334   
urgent                       0.017884   0.000094   0.007234 -0.000019   
hot                          0.108639   0.113920   0.193156 -0.000538   
num_failed_logins            0.014363  -0.008396   0.021952 -0.000075   
logged_in                    0.159564  -0.089702   0.882185 -0.002784   
num_compromised              0.010687   0.118562   0.169772 -0.000449   
root_shell                   0.040425   0.003067   0.026054 -0.000070   
su_attempted                 0.026012   0.002282   0.012191 -0.000033   
num_root                     0.013401  -0.002050  -0.003884 -0.000230   
num_file_creations           0.061099   0.027710   0.034154 -0.000155   
num_shells                   0.008633   0.014403  -0.000055 -0.000068   
num_access_files             0.019407  -0.001497   0.065775 -0.000202   
num_outbound_cmds                 NaN        NaN        NaN       NaN   
is_hot_login                      NaN        NaN        NaN       NaN   
is_guest_login               0.205607   0.027511   0.085947 -0.000249   
count                       -0.259032   0.666230  -0.639157 -0.010939   
srv_count                   -0.250139   0.722609  -0.497683 -0.010128   
serror_rate                 -0.074211  -0.657460  -0.205848  0.014160   
srv_serror_rate             -0.073663  -0.652391  -0.198715  0.014343   
rerror_rate                 -0.025936  -0.342180  -0.100958 -0.000452   
srv_rerror_rate             -0.026420  -0.332977  -0.081307 -0.001688   
same_srv_rate                0.062291   0.744046   0.229677  0.002153   
diff_srv_rate               -0.050875  -0.739988  -0.222572 -0.001846   
srv_diff_host_rate           0.123621  -0.104042   0.521003  0.020680   
dst_host_count              -0.161107   0.130377  -0.611972 -0.019922   
dst_host_srv_count          -0.217167   0.741979   0.024124 -0.012342   
dst_host_same_srv_rate      -0.211979   0.729151   0.055033  0.002574   
dst_host_diff_srv_rate       0.231644  -0.712965  -0.035073 -0.001803   
dst_host_same_src_port_rate -0.065202   0.815039  -0.396195  0.004265   
dst_host_srv_diff_host_rate  0.100692  -0.140231   0.578557  0.016173   
dst_host_serror_rate        -0.056753  -0.645919  -0.167047  0.013565   
dst_host_srv_serror_rate    -0.057298  -0.641792  -0.158378  0.012264   
dst_host_rerror_rate        -0.007759  -0.297338  -0.003042  0.000386   
dst_host_srv_rerror_rate    -0.013891  -0.300581   0.001621 -0.001820   

                             wrong_fragment    urgent       hot  \
duration                          -0.008025  0.017884  0.108639   
src_bytes                         -0.019358  0.000094  0.113920   
dst_bytes                         -0.022659  0.007234  0.193156   
land                              -0.000334 -0.000019 -0.000538   
wrong_fragment                     1.000000 -0.000143 -0.004042   
urgent                            -0.000143  1.000000  0.008596   
hot                               -0.004042  0.008596  1.000000   
num_failed_logins                 -0.000566  0.062973  0.112558   
logged_in                         -0.020911  0.006821  0.189126   
num_compromised                   -0.003371  0.031781  0.811529   
root_shell                        -0.000529  0.067394  0.101986   
su_attempted                      -0.000247 -0.000014 -0.000397   
num_root                          -0.001726  0.061989  0.003096   
num_file_creations                -0.001161  0.061373  0.028693   
num_shells                        -0.000509 -0.000029  0.009144   
num_access_files                  -0.001520  0.023389  0.004223   
num_outbound_cmds                       Na